version: '3.8'

services:
  discord-mcp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./config:/app/config:ro
    restart: unless-stopped